[general]
output = "NuMI_numu_data"

[[sample]]
name = "data"
path = "/pnfs/icarus/persistent/users/dcarber/spine/NuMI_data_flat_cafs_2/*.flat.root"
ismc = false

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "data_quality_cut", type = "event"},
    {name = "fiducial_cut", type = "reco"},
    {name = "containment_cut", type = "reco"},
    {name = "valid_flashmatch", type = "reco"},
    {name = "all_1muNp_cut", type = "reco"},

]
branch = [
    {name = "neutrino_id", type = "true"},
    #{name = "baseline", type = "mctruth"},
    #{name = "cc", type = "mctruth"},
    #{name = "pdg", type = "mctruth"},
    #{name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    #{name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dpT_lp", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "opening_angle", type = "both"},
    {name = "flash_time", type = "reco"},
]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "fiducial_cut", type = "true"},
    {name = "containment_cut", type = "true"},
    {name = "neutrino", type = "true"},
    {name = "all_1muNp_cut", type = "true"},
]
branch = [
    {name = "neutrino_id", type = "true"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "pdg", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "true"},
    {name = "dpT", type = "true"},
    {name = "dpT_lp", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "opening_angle", type = "both"},
    {name = "fiducial", type = "reco"},
    {name = "containment", type = "reco"},
    {name = "flash_time", type = "reco"},
]
[[tree]]
name = "exposure"
sim_only = false
mode = "event"
cut = [
    #{name = "data_quality_cut", type = "event"},
]
branch = [
    {name = "pot", type = "event"},
    {name = "pot_from_spillinfo", type = "event", parameters = [1.0,]},
    {name = "nbnb", type = "event"},
    {name = "nnumi", type = "event"},
    {name = "noffbeambnb", type = "event"},
    {name = "noffbeamnumi", type = "event"},
    {name = "ngenevt", type = "event"},
    {name = "is_first_in_subrun", type = "event"},
]
