[general]
output = "NuMI_nu_test_2"

[[sample]]
name = "simulation"
path = "/pnfs/icarus/persistent/users/dcarber/spine/combined_files/NuMI_CV_flat_cafs_2/*.flat.root"
ismc = true

[[tree]]
name = "selected"
sim_only = false
mode = "reco"
cut = [
    {name = "fiducial_cut", type = "reco"},
    {name = "containment_cut", type = "reco"},
    {name = "valid_flashmatch", type = "reco"},
    {name = "flash_cut", type = "reco", parameters = [0,9.6]},
    {name = "all_1muNp_cut", type = "reco"},
]
branch = [
    {name = "neutrino_id", type = "true"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "pdg", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "both"},
    {name = "dpT", type = "both"},
    {name = "dpT_lp", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "opening_angle", type = "both"},
    {name = "flash_time", type = "reco"},

# Leading MUON interaction-level
    { name = "end_x",             type = "both_particle", selector = "leading_muon"   },
    { name = "end_y",             type = "both_particle", selector = "leading_muon"   },
    { name = "end_z",             type = "both_particle", selector = "leading_muon"   },
    { name = "ke",                type = "both_particle", selector = "leading_muon"   },
    { name = "length",            type = "both_particle", selector = "leading_muon"   },
    { name = "dpT",               type = "both_particle", selector = "leading_muon"   },
    { name = "polar_angle",       type = "both_particle", selector = "leading_muon"   },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_muon"   },
    { name = "primary_softmax",   type = "reco_particle", selector = "leading_muon"   },
    { name = "secondary_softmax", type = "reco_particle", selector = "leading_muon"   },
    { name = "muon_softmax",      type = "reco_particle", selector = "leading_muon"   },
    { name = "pion_softmax",      type = "reco_particle", selector = "leading_muon"   },
    { name = "proton_softmax",    type = "reco_particle", selector = "leading_muon"   },
    { name = "mip_softmax",       type = "reco_particle", selector = "leading_muon"   },
    { name = "hadron_softmax",    type = "reco_particle", selector = "leading_muon"   },

    # Leading PROTON interaction-level
    { name = "end_x",             type = "both_particle", selector = "leading_proton" },
    { name = "end_y",             type = "both_particle", selector = "leading_proton" },
    { name = "end_z",             type = "both_particle", selector = "leading_proton" },
    { name = "ke",                type = "both_particle", selector = "leading_proton" },
    { name = "length",            type = "both_particle", selector = "leading_proton" },
    { name = "dpT",               type = "both_particle", selector = "leading_proton" },
    { name = "polar_angle",       type = "both_particle", selector = "leading_proton" },
    { name = "azimuthal_angle",   type = "both_particle", selector = "leading_proton" },
    { name = "primary_softmax",   type = "reco_particle", selector = "leading_proton" },
    { name = "secondary_softmax", type = "reco_particle", selector = "leading_proton" },
    { name = "muon_softmax",      type = "reco_particle", selector = "leading_proton" },
    { name = "pion_softmax",      type = "reco_particle", selector = "leading_proton" },
    { name = "proton_softmax",    type = "reco_particle", selector = "leading_proton" },
    { name = "mip_softmax",       type = "reco_particle", selector = "leading_proton" },
    { name = "hadron_softmax",    type = "reco_particle", selector = "leading_proton" },

 # Kinematic imbalance & angles
    { name = "opening_angle", type = "both" },
    { name = "dpT",           type = "both" },
    { name = "dpT_lp",        type = "both" },
    { name = "dphiT",         type = "both" },

]

[[tree]]
name = "signal"
sim_only = true
mode = "true"
cut = [
    {name = "fiducial_cut", type = "true"},
    {name = "containment_cut", type = "true"},
    {name = "neutrino", type = "true"},
    {name = "all_1muNp_cut", type = "true"},
]
branch = [
    {name = "neutrino_id", type = "true"},
    {name = "baseline", type = "mctruth"},
    {name = "cc", type = "mctruth"},
    {name = "pdg", type = "mctruth"},
    {name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "true"},
    {name = "dpT", type = "true"},
    {name = "dpT_lp", type = "both"},
    {name = "dphiT", type = "both"},
    {name = "dalphaT", type = "both"},
    {name = "opening_angle", type = "both"},
    {name = "fiducial", type = "reco"},
    {name = "containment", type = "reco"},
    {name = "flash_time", type = "reco"},
]

[[tree]]
name = "neutrino_cut"
sim_only = true
mode = "true"
cut = [
    {name = "signal_1eNp", type = "true"},
]
branch = [
    {name = "neutrino_id", type = "true"},
    #{name = "baseline", type = "mctruth"},
    #{name = "cc", type = "mctruth"},
    #{name = "pdg", type = "mctruth"},
    #{name = "interaction_type", type = "mctruth"},
    {name = "category", type = "true"},
    {name = "neutrino_energy", type = "mctruth"},
    {name = "visible_energy", type = "true"},
    {name = "dpT", type = "both"},
#    {name = "dpT_lp", type = "both"},
#    {name = "dphiT", type = "both"},
#    {name = "dalphaT", type = "both"},
#    {name = "opening_angle", type = "both"},
#    {name = "fiducial", type = "reco"},
#    {name = "containment", type = "reco"},
#    {name = "flash_time", type = "reco"},
]
