
[[this_includes]]
file = 'configurations/analyses/icarus/nue2025_icarus.toml'

[[this_includes]]
file = 'configurations/common/styles.toml'

[samples]
[samples.onbeam]
key = "onbeam"
exposure_type = "pot"
override_category = -100
trees = ['SelectedNu_PhaseCuts',]
[samples.offbeam]
key = "offbeam"
exposure_type = "Livetime"
override_category = -1
trees = ['SelectedCos_PhaseCuts',]
[samples.mc_nu]
key = "mc"
exposure_type = "pot"
trees = ['SelectedNu_Cuts']
presel = 'matches_baseline == 1'
systematics = ['multisimTree']
print_sys = true
[samples.mc_cos]
key = "mc"
exposure_type = "pot"
trees = ['SelectedCos_PhaseCuts']
#presel = 'matches_baseline == 1'
#systematics = ['multisimTree']
#[samples.mc]
#key = "mc"
#exposure_type = "pot"
#trees = ['SelectedNu_Cuts','SelectedCos_PhaseCuts']



[output]
path = '/Users/danielcarber/Documents/ICARUS/NuMI_Nue/Plots'

[[systematic_recipe]]
name = 'flux'
label = 'Flux Systematics'
#pattern = '_Flux'
pattern = '\b\w*_Flux\b'

[[systematic_recipe]]
name = 'xsec'
label = 'Interaction Systematics'
pattern = '\bGENIEReWeight_SBN_v1_multisim_\w+\b'
#pattern = 'GENIEReWeight_SBN_v1_multisim'


[[systematic_recipe]]
name = 'stats'
label = 'Statistical Uncertainty'
#pattern = 'mc_statistical'
pattern = '(mc_nu|mc_cos|offbeam)_statistical'
#pattern = '(mc|offbeam)_statistical'

#[[systematic_recipe]]
#name = 'offbeam_stats'
#label = 'Statistical Uncertainty'
#pattern = 'mc_statistical'
#pattern = '(mc_nu|mc_cos|offbeam)_statistical'
#pattern = '(offbeam)_statistical'

#[[systematic_recipe]]
#name = 'MC_stats'
#label = 'Statistical Uncertainty'
#pattern = 'mc_statistical'
#pattern = '(mc_nu|mc_cos)_statistical'
#pattern = '(offbeam)_statistical'

[[systematic_recipe]]
name = 'flux_xsec'
label = 'Flux + Interaction Uncertainty'
pattern = '(flux|xsec|stats)'
                
#[[systematic_recipe]]
#name = 'all'
#label = 'Total MC Uncertainty'
#pattern = '(flux|xsec|stats)'
#pattern = '(detsys|flux|xsec|stats)'


[analysis]
ordinate_sample = 'onbeam'
category_branch = 'category_topology'
category_assignment = [[0,1], [2,3,4,6], [5], [7],[8],[9],[11,-1], [-100]]
category_labels = ['1eNp', 'Other CC $\nu_e$', 'NC $\nu$', '$\nu_\mu$ CC','OOFVS','Other','Cosmic', 'Run 2 Data']
category_colors = ['C0', 'C1', 'C3', 'C4', 'C5','C6','C7','black']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram','histogram', 'histogram', 'scatter']


[[figure]]
name = 'reco_electron_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_energy'},]
style = 'selected_icarus'

[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_energy'
range = [70, 3000]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_electron_pT_mag'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_pT_mag'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_pT_mag'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_electron_conv_dist'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_conv_dist'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_conv_dist'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_electron_axial_spread'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_axial_spread'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_axial_spread'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_electron_dir_spread'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_dir_spread'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_dir_spread'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_proton_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_proton_softmax'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_proton_softmax'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}
[[figure]]
name = 'reco_dpT'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_dpT'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dpT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}
[[figure]]
name = 'reco_electron_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_softmax'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_softmax'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_electron_dedx'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_dedx'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_dedx'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_opening_angle'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_opening_angle'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_opening_angle'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_dalphaT'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_dalphaT'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dalphaT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_dphiT'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_dphiT'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_dphiT'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_NuMI_polar'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_NuMI_polar'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_NuMI_polar'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_NuMI_azi'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_NuMI_azi'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_NuMI_azi'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}

[[figure]]
name = 'reco_proton_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_proton_energy'},]
style = 'selected_icarus'
[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_proton_energy'
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true, 'invert_stack_order' = true, 'draw_error' = 'flux_xsec'}



