[variables]

[variables.reco_electron_energy]
key = 'reco_electron_energy'
range = [0,3000]
nbins = 30
xlabel = 'Reconstructed Electorn Energy [MeV]'

[variables.reco_electron_pT_mag]
key = 'reco_electron_pT_mag'
range = [0,1000]
nbins = 20
xlabel = 'Reconstructed Electron Transverse Momentum [MeV/c]'

[variables.reco_electron_conv_dist]
key = 'reco_electron_conv_dist'
range = [0,100]
nbins = 25
xlabel = 'Reconstructed Electron Conversion Distance [MeV]'

[variables.reco_electron_axial_spread]
key = 'reco_electron_axial_spread'
range = [-1,1]
nbins = 40
xlabel = 'Reconstructed Eelctron Axial Spread'

[variables.reco_electron_dir_spread]
key = 'reco_electron_dir_spread'
range = [0,1]
nbins = 40
xlabel = 'Reconstructed Electron Directional Spread'

[variables.reco_electron_softmax]
key = 'reco_electron_softmax'
range = [0,1]
nbins =	25
xlabel = 'Reconstructed Electron Softmax'

[variables.reco_electron_primary_score]
key = 'reco_electron_primary_score'
range = [0,1]
nbins = 50
xlabel = 'Reconstructed Electron Primary Score]'

[variables.reco_proton_softmax]
key = 'reco_proton_softmax'
range = [0,1]
nbins =	25
xlabel = 'Reconstructed Proton Softmax'

[variables.reco_proton_muon_softmax]
key = 'reco_proton_softmax'
range = [0,1]
nbins =	25
xlabel = "Reconstructed Proton's Muon Softmax"

[variables.reco_proton_pion_softmax]
key = 'reco_proton_softmax'
range = [0,1]
nbins =	25
xlabel = "Reconstructed Proton's Pion Softmax"

[output]
path = '/exp/icarus/app/users/dcarber/spine_analysis/plots'

[analysis]
ordinate_sample = 'mc'
category_branch = 'category_topology'
category_assignment = [[0,1], [2346], [5], [7],[8],[9], [-100]]
category_labels = ['1$e$Np', 'Other CC $\nu$e', 'NC $\nu$', '$\nu\mu$ CC','Uncontained','Cosmic', 'Run 2 Data']
category_colors = ['C0', 'C1', 'C3', 'C4', 'C5','C6','C2']
category_types = ['histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'histogram', 'scatter']

[[this_includes]]
file = 'configurations/common/samples.toml'
choose = {'samples' = ['mc']}

[[this_includes]]
file = 'configurations/common/styles.toml'

[[figure]]
name = 'reco_electron_energy'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_energy'},]
style = 'selected_icarus'

name = 'reco_electron_pT_mag'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_pT_mag'},]
style = 'selected_icarus'

name = 'reco_electron_conv_dist'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_conv_dist'},]
style = 'selected_icarus'

name = 'reco_electron_axial_spread'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_axial_spread'},]
style = 'selected_icarus'

name = 'reco_electron_dir_spread'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_dir_spread'},]
style = 'selected_icarus'

name = 'reco_electron_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_softmax'},]
style = 'selected_icarus'

name = 'reco_electron_primary_score'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_electron_primary_score'},]
style = 'selected_icarus'

name = 'reco_proton_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_proton_softmax'},]
style = 'selected_icarus'

name = 'reco_proton_muon_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_proton_muon_softmax'},]
style = 'selected_icarus'

name = 'reco_proton_pion_softmax'
type = 'SimpleFigure'
artists = [{'type' = 'SpineSpectra1D', 'variable' = 'reco_proton_pion_softmax'},]
style = 'selected_icarus'


[[figure.artists]]
type = 'SpineSpectra1D'
variable = 'reco_electron_energy'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_electron_pT_mag'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_electron_conv_dist'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_electron_axial_spread'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_electron_dir_spread'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_electron_softmax'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}
type = 'SpineSpectra1D'
variable = 'reco_electron_primary_score'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_proton_softmax'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_proton_muon_softmax'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

type = 'SpineSpectra1D'
variable = 'reco_proton_pion_softmax'
#yrange = [0, 120]
draw_kwargs = {'show_component_number' = true, 'show_component_percentage' = true,}

#[variables.true_neutrino_energy]
#key = 'true_edep'
#range = [0,6]
#nbins = 30
#xlabel = 'True Neutrino Energy [GeV]'